name: Python Selenium Tests with Firefox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Instala pytest diretamente, como garantia
        pip list  # Verifica as dependências instaladas

    - name: Run Selenium tests on Firefox
      run: |
        Xvfb :99 &  # Inicia um display virtual para execução headless
        export DISPLAY=:99
        which pytest  # Verifica o caminho do pytest para garantir a instalação
        pytest tests/